services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: hms
      POSTGRES_PASSWORD: hms
      POSTGRES_DB: hms
    ports:
      - "5432:5432"
    volumes:
      - hms_pgdata:/var/lib/postgresql/data

volumes:
  hms_pgdata:
